import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto'
import type { FieldClass } from '@gadong/kernel'

/**
 * Ciphertext layout, per `docs/superpowers/plans/00-PROGRAM-ROADMAP.md`
 * "Contracts every phase depends on" (revised 2026-08-02, Task 6 fix round 1):
 *
 *   u8(version) ‖ u8(fieldClass) ‖ u16be(len(wrappedDEK)) ‖ wrappedDEK ‖ nonce(12) ‖ ct ‖ tag(16)
 *
 * The 2-byte big-endian length prefix makes the wrappedDEK's extent
 * self-describing — without it a reader has no delimiter between the
 * (variable-length, opaque) wrappedDEK and the fixed-length nonce/ct/tag
 * that follow it, so nothing beyond a total-length check could ever be
 * validated. The 1-byte `fieldClass` makes the envelope self-describing
 * about *which* KEK unwraps it: `decrypt`'s wire contract carries no
 * `fieldClass` (fixed by the already-merged `CryptoClient`), and the
 * original fix — trying `kek-s2` then `kek-s3` until one worked — traded
 * away exactly the distinction this exists to preserve: "Vault is sealed"
 * (operational, self-healing once officers unseal) versus "no KEK can
 * unwrap this ciphertext" (a data-integrity alarm — tampering or a wrong-key
 * restore) collapsed into one indistinguishable `CRY-503`, S3 (the hot
 * class: salaries, national IDs, bank accounts) paid a second Vault round
 * trip on every decrypt, and a third class would have made it worse. Reading
 * `fieldClass` from the header makes `decrypt` unwrap under exactly one KEK,
 * always. The 1-byte `version` (currently always 1) exists because there is
 * no deployed data anywhere yet — free to add now, expensive as a migration
 * later. `seal`/`open` are pure functions over an already-unwrapped 32-byte
 * DEK; the Vault round-trip that produces `wrappedDek` and the plaintext
 * `dek` lives in `vault.client.ts`, not here, so this module is fully
 * unit-testable without Vault.
 */
const VERSION = 1
const HEADER_BYTES = 4 // version(1) + fieldClass(1) + u16be length(2)
const NONCE_BYTES = 12
const TAG_BYTES = 16
const DEK_BYTES = 32
const ALGORITHM = 'aes-256-gcm'
const MAX_WRAPPED_DEK_BYTES = 0xffff // u16be ceiling

const FIELD_CLASS_CODE: Record<FieldClass, number> = { S2: 2, S3: 3 }
const FIELD_CLASS_BY_CODE = new Map<number, FieldClass>(
  (Object.entries(FIELD_CLASS_CODE) as [FieldClass, number][]).map(([cls, code]) => [code, cls]),
)

/**
 * AAD = `entityId + ':' + field` (roadmap's data-classification contract; also
 * `global-constraints.md`). This is what stops ciphertext being swapped between
 * rows or fields: `open()` below cannot succeed unless the caller supplies the
 * exact same AAD that was present at seal time, because GCM authenticates the
 * AAD as part of the tag. Deliberately unchanged by the fieldClass-header fix
 * (Task 6 fix round 1) — this was mutation-tested and verified load-bearing.
 */
export function buildAad(entityId: string, field: string): Buffer {
  return Buffer.from(`${entityId}:${field}`, 'utf8')
}

/**
 * Encrypts `plaintext` under `dek` (AES-256-GCM) with `aad` bound into the
 * authentication tag, then assembles the full wire layout: version,
 * `fieldClass` (so a later `decrypt` never has to guess which KEK unwraps
 * this envelope), the length-prefixed `wrappedDek` (opaque bytes from Vault
 * Transit — this function never inspects or validates their content, only
 * their length, since it needs the length to write the u16be header),
 * nonce, ciphertext, and tag.
 *
 * `dek` is the 32-byte *plaintext* data key — already unwrapped by the
 * caller when this is used for `open`, or freshly generated by Vault when
 * used for `seal`. This function never talks to Vault and never persists
 * `dek` itself; the caller is responsible for discarding it after use.
 */
export function seal(dek: Buffer, wrappedDek: Buffer, fieldClass: FieldClass, aad: Buffer, plaintext: Buffer): Buffer {
  if (dek.length !== DEK_BYTES) {
    throw new Error(`envelope.seal: dek must be exactly ${DEK_BYTES} bytes, got ${dek.length}`)
  }
  if (wrappedDek.length > MAX_WRAPPED_DEK_BYTES) {
    throw new Error(`envelope.seal: wrappedDek (${wrappedDek.length} bytes) exceeds the u16be length-prefix ceiling`)
  }

  const nonce = randomBytes(NONCE_BYTES)
  const cipher = createCipheriv(ALGORITHM, dek, nonce)
  cipher.setAAD(aad)
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()])
  const tag = cipher.getAuthTag()

  const header = Buffer.alloc(HEADER_BYTES)
  header.writeUInt8(VERSION, 0)
  header.writeUInt8(FIELD_CLASS_CODE[fieldClass], 1)
  header.writeUInt16BE(wrappedDek.length, 2)

  return Buffer.concat([header, wrappedDek, nonce, ct, tag])
}

export interface EnvelopeHeader {
  version: number
  fieldClass: FieldClass
  wrappedDek: Buffer
}

/**
 * Parses the fixed header — version, fieldClass, and the length-prefixed
 * `wrappedDek` — without touching the DEK or decrypting anything.
 * `crypto.service.ts` calls this first (before it has a plaintext DEK at
 * all) to learn exactly which single KEK to ask Vault to unwrap under.
 *
 * Never trusts the header past validation: an unrecognised `version`, an
 * unrecognised `fieldClass` byte, or a declared `wrappedDek` length longer
 * than the remaining buffer all throw rather than being silently accepted,
 * defaulted, or clamped (Task 6 brief §1, "a declared `len(wrappedDEK)`
 * larger than the remaining buffer → throws"; fix round 1, "reject any
 * other [fieldClass] value — do not default").
 */
export function parseHeader(envelope: Buffer): EnvelopeHeader {
  if (envelope.length < HEADER_BYTES) {
    throw new Error('envelope.parseHeader: buffer shorter than the 4-byte header')
  }
  const version = envelope.readUInt8(0)
  if (version !== VERSION) {
    throw new Error(`envelope.parseHeader: unsupported version ${version}`)
  }
  const classCode = envelope.readUInt8(1)
  const fieldClass = FIELD_CLASS_BY_CODE.get(classCode)
  if (fieldClass === undefined) {
    throw new Error(`envelope.parseHeader: unrecognised fieldClass code ${classCode}`)
  }
  const wrappedLen = envelope.readUInt16BE(2)
  const wrappedEnd = HEADER_BYTES + wrappedLen
  if (wrappedEnd > envelope.length) {
    throw new Error(
      `envelope.parseHeader: header declares ${wrappedLen}-byte wrappedDek but only ${envelope.length - HEADER_BYTES} bytes remain`,
    )
  }
  return { version, fieldClass, wrappedDek: envelope.subarray(HEADER_BYTES, wrappedEnd) }
}

/**
 * Decrypts `envelope` using the already-unwrapped `dek` and the AAD the
 * caller reconstructed from `entityId:field`. Throws — never returns a
 * partial or garbage value — on any structural problem (truncation, an
 * unrecognised version/fieldClass, an over-long declared wrappedDek
 * length), any tamper (a flipped bit in the ciphertext or tag), or any AAD
 * mismatch (wrong entityId or field): GCM's `decipher.final()` rejects
 * unless the tag verifies against exactly the ciphertext and AAD given,
 * which is what makes AAD binding load-bearing rather than advisory.
 */
export function open(dek: Buffer, aad: Buffer, envelope: Buffer): Buffer {
  if (dek.length !== DEK_BYTES) {
    throw new Error(`envelope.open: dek must be exactly ${DEK_BYTES} bytes, got ${dek.length}`)
  }

  const { wrappedDek } = parseHeader(envelope) // validates version/fieldClass/length prefix/truncation
  const rest = envelope.subarray(HEADER_BYTES + wrappedDek.length)

  if (rest.length < NONCE_BYTES + TAG_BYTES) {
    throw new Error(
      `envelope.open: buffer truncated — only ${rest.length} bytes after wrappedDek, need at least ${NONCE_BYTES + TAG_BYTES} for nonce+tag`,
    )
  }

  const nonce = rest.subarray(0, NONCE_BYTES)
  const tag = rest.subarray(rest.length - TAG_BYTES)
  const ct = rest.subarray(NONCE_BYTES, rest.length - TAG_BYTES)

  const decipher = createDecipheriv(ALGORITHM, dek, nonce)
  decipher.setAAD(aad)
  decipher.setAuthTag(tag)
  // `final()` throws GCM's tag-verification failure here — this is the one
  // line that makes tamper detection and AAD binding both real: there is no
  // path that returns `update()`'s output without also calling `final()`.
  return Buffer.concat([decipher.update(ct), decipher.final()])
}
