import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto'

/**
 * Ciphertext layout, per `docs/superpowers/plans/00-PROGRAM-ROADMAP.md`
 * "Contracts every phase depends on" (revised 2026-08-02, Task 3 review):
 *
 *   u16be(len(wrappedDEK)) ‖ wrappedDEK ‖ nonce(12) ‖ ct ‖ tag(16)
 *
 * The 2-byte big-endian length prefix makes the wrappedDEK's extent
 * self-describing — without it a reader has no delimiter between the
 * (variable-length, opaque) wrappedDEK and the fixed-length nonce/ct/tag
 * that follow it, so nothing beyond a total-length check could ever be
 * validated. `seal`/`open` are pure functions over an already-unwrapped
 * 32-byte DEK; the Vault round-trip that produces `wrappedDek` and the
 * plaintext `dek` lives in `vault.client.ts`, not here, so this module is
 * fully unit-testable without Vault.
 */
const LENGTH_PREFIX_BYTES = 2
const NONCE_BYTES = 12
const TAG_BYTES = 16
const DEK_BYTES = 32
const ALGORITHM = 'aes-256-gcm'
const MAX_WRAPPED_DEK_BYTES = 0xffff // u16be ceiling

/**
 * AAD = `entityId + ':' + field` (roadmap's data-classification contract; also
 * `global-constraints.md`). This is what stops ciphertext being swapped between
 * rows or fields: `open()` below cannot succeed unless the caller supplies the
 * exact same AAD that was present at seal time, because GCM authenticates the
 * AAD as part of the tag.
 */
export function buildAad(entityId: string, field: string): Buffer {
  return Buffer.from(`${entityId}:${field}`, 'utf8')
}

/**
 * Encrypts `plaintext` under `dek` (AES-256-GCM) with `aad` bound into the
 * authentication tag, then assembles the full wire layout by prefixing the
 * caller-supplied `wrappedDek` (opaque bytes from Vault Transit — this
 * function never inspects or validates their content, only their length,
 * since it needs the length to write the u16be header) with its length.
 *
 * `dek` is the 32-byte *plaintext* data key — already unwrapped by the
 * caller when this is used for `open`, or freshly generated by Vault when
 * used for `seal`. This function never talks to Vault and never persists
 * `dek` itself; the caller is responsible for discarding it after use.
 */
export function seal(dek: Buffer, wrappedDek: Buffer, aad: Buffer, plaintext: Buffer): Buffer {
  if (dek.length !== DEK_BYTES) {
    throw new Error(`envelope.seal: dek must be exactly ${DEK_BYTES} bytes, got ${dek.length}`)
  }
  if (wrappedDek.length > MAX_WRAPPED_DEK_BYTES) {
    throw new Error(`envelope.seal: wrappedDek (${wrappedDek.length} bytes) exceeds the u16be length-prefix ceiling`)
  }

  const nonce = randomBytes(NONCE_BYTES)
  const cipher = createCipheriv(ALGORITHM, dek, nonce)
  cipher.setAAD(aad)
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()])
  const tag = cipher.getAuthTag()

  const header = Buffer.alloc(LENGTH_PREFIX_BYTES)
  header.writeUInt16BE(wrappedDek.length, 0)

  return Buffer.concat([header, wrappedDek, nonce, ct, tag])
}

/**
 * Parses only the `wrappedDek` segment out of a full envelope, without
 * touching the DEK or decrypting anything. `crypto.service.ts` calls this
 * first (before it has a plaintext DEK at all) to learn what to hand Vault
 * for unwrapping.
 *
 * The declared length is never trusted past the buffer's actual size: a
 * header claiming more bytes than remain throws rather than silently
 * clamping or reading out of bounds (Task 6 brief §1, "a declared
 * `len(wrappedDEK)` larger than the remaining buffer → throws").
 */
export function peekWrappedDek(envelope: Buffer): Buffer {
  if (envelope.length < LENGTH_PREFIX_BYTES) {
    throw new Error('envelope.peekWrappedDek: buffer shorter than the 2-byte length prefix')
  }
  const wrappedLen = envelope.readUInt16BE(0)
  const wrappedEnd = LENGTH_PREFIX_BYTES + wrappedLen
  if (wrappedEnd > envelope.length) {
    throw new Error(
      `envelope.peekWrappedDek: header declares ${wrappedLen}-byte wrappedDek but only ${envelope.length - LENGTH_PREFIX_BYTES} bytes remain`,
    )
  }
  return envelope.subarray(LENGTH_PREFIX_BYTES, wrappedEnd)
}

/**
 * Decrypts `envelope` using the already-unwrapped `dek` and the AAD the
 * caller reconstructed from `entityId:field`. Throws — never returns a
 * partial or garbage value — on any structural problem (truncation, an
 * over-long declared wrappedDek length), any tamper (a flipped bit in the
 * ciphertext or tag), or any AAD mismatch (wrong entityId or field): GCM's
 * `decipher.final()` rejects unless the tag verifies against exactly the
 * ciphertext and AAD given, which is what makes AAD binding load-bearing
 * rather than advisory.
 */
export function open(dek: Buffer, aad: Buffer, envelope: Buffer): Buffer {
  if (dek.length !== DEK_BYTES) {
    throw new Error(`envelope.open: dek must be exactly ${DEK_BYTES} bytes, got ${dek.length}`)
  }

  const wrappedDek = peekWrappedDek(envelope) // validates the length prefix / truncation
  const rest = envelope.subarray(LENGTH_PREFIX_BYTES + wrappedDek.length)

  if (rest.length < NONCE_BYTES + TAG_BYTES) {
    throw new Error(
      `envelope.open: buffer truncated — only ${rest.length} bytes after wrappedDek, need at least ${NONCE_BYTES + TAG_BYTES} for nonce+tag`,
    )
  }

  const nonce = rest.subarray(0, NONCE_BYTES)
  const tag = rest.subarray(rest.length - TAG_BYTES)
  const ct = rest.subarray(NONCE_BYTES, rest.length - TAG_BYTES)

  const decipher = createDecipheriv(ALGORITHM, dek, nonce)
  decipher.setAAD(aad)
  decipher.setAuthTag(tag)
  // `final()` throws GCM's tag-verification failure here — this is the one
  // line that makes tamper detection and AAD binding both real: there is no
  // path that returns `update()`'s output without also calling `final()`.
  return Buffer.concat([decipher.update(ct), decipher.final()])
}
